// src/models/Account.ts
//
// ─── SINGLE RESPONSIBILITY ─────────────────────────────────────────────────────
// This file defines the Account schema and exports the Mongoose model.
// Nothing else. No seed data. No helper functions. No business logic.
//
// Seed data lives in:  src/lib/seed/accounts.seed.ts
// Business logic lives in: src/lib/services/accounting.service.ts
// ─────────────────────────────────────────────────────────────────────────────

import mongoose, { Schema, Document, Model } from 'mongoose'

// ─── ACCOUNT TYPES ────────────────────────────────────────────────────────────
// The 5 universal account types used in double-entry bookkeeping.
// These map to the standard Lebanese/French accounting chart (PCG).
//
//   1xxx → ASSET      Things you own  (Cash, Inventory)
//   2xxx → LIABILITY  Things you owe  (Loans, Payables)
//   3xxx → EQUITY     Owner's stake   (Capital, Retained Earnings)
//   4xxx → REVENUE    Money coming in (Sales)
//   5xxx → EXPENSE    Money going out (Salaries, Rent, Purchases)

export type AccountType =
  | 'asset'
  | 'liability'
  | 'equity'
  | 'revenue'
  | 'expense'

// ─── ACCOUNT SUBTYPES ─────────────────────────────────────────────────────────
// Subtypes allow other modules to find the right account without hardcoding
// document IDs. The purchase module looks up subtype:'raw_material_purchase',
// the POS module looks up subtype:'sales'. If the account is renamed or
// the code changes, the lookup still works.

export type AccountSubtype =
  // Asset subtypes
  | 'cash'                   // Physical cash drawer (USD or LBP)
  | 'bank'                   // Bank account
  | 'accounts_receivable'    // Money owed TO you
  | 'inventory'              // Raw materials on hand (AVCO-valued)
  | 'fixed_asset'            // Equipment, furniture, vehicles
  | 'other_asset'
  // Liability subtypes
  | 'accounts_payable'       // Money you owe to suppliers
  | 'loan'                   // Bank loans
  | 'other_liability'
  // Equity subtypes
  | 'owners_equity'
  | 'retained_earnings'
  | 'other_equity'
  // Revenue subtypes
  | 'sales'                  // POS and online sales → auto-posted by POS module
  | 'other_income'
  // Expense subtypes
  | 'raw_material_purchase'  // Ingredient/material purchases → auto-posted by Purchase module
  | 'cogs'                   // Cost of Goods Sold (future: per-order AVCO costing)
  | 'salary'                 // Staff wages → Expense module
  | 'rent'                   // Shop/kitchen rent → Expense module
  | 'utility'                // Electricity, water, internet → Expense module
  | 'equipment'              // Small equipment or repairs → Expense module
  | 'marketing'              // Ads, promotions → Expense module
  | 'other_expense'          // Anything else

// ─── CODE RANGES ──────────────────────────────────────────────────────────────
// Used by the service layer to auto-generate sequential account codes.
// Manager never enters a code — the system assigns the next available one.
export const ACCOUNT_CODE_RANGES: Record<AccountType, { start: number; end: number }> = {
  asset:     { start: 1000, end: 1999 },
  liability: { start: 2000, end: 2999 },
  equity:    { start: 3000, end: 3999 },
  revenue:   { start: 4000, end: 4999 },
  expense:   { start: 5000, end: 5999 },
}

export interface IAccount extends Document {
  _id:  mongoose.Types.ObjectId

  // Code is auto-generated by the service — manager never types it
  code:   string        // "5000", "5001", "5002" ...
  name:   string        // "Raw Material Purchases"
  nameAr: string        // "مشتريات المواد الخام"

  type:    AccountType
  subtype: AccountSubtype

  // Derived flags — set automatically based on type, not by the manager
  isIncomeStatement: boolean   // true for revenue + expense (→ P&L)
  isBalanceSheet:    boolean   // true for asset + liability + equity (→ Balance Sheet)

  // System accounts are auto-posted by other modules (Purchase, POS).
  // They can't be deleted by the manager because doing so would break
  // automatic journal entry creation.
  // The manager CAN rename them but cannot delete or deactivate them.
  isSystem: boolean

  isActive: boolean
  description: string

  createdBy: mongoose.Types.ObjectId | null   // null for seeded system accounts
  createdAt: Date
  updatedAt: Date
}

const AccountSchema = new Schema<IAccount>(
  {
    code:   { type: String, required: true, unique: true, trim: true },
    name:   { type: String, required: true, trim: true },
    nameAr: { type: String, default: '',   trim: true },

    type: {
      type: String,
      enum: ['asset', 'liability', 'equity', 'revenue', 'expense'],
      required: true,
    },
    subtype: {
      type: String,
      enum: [
        'cash', 'bank', 'accounts_receivable', 'inventory', 'fixed_asset', 'other_asset',
        'accounts_payable', 'loan', 'other_liability',
        'owners_equity', 'retained_earnings', 'other_equity',
        'sales', 'other_income',
        'raw_material_purchase', 'cogs', 'salary', 'rent',
        'utility', 'equipment', 'marketing', 'other_expense',
      ],
      required: true,
    },

    // Set by the service layer, not by the manager
    isIncomeStatement: { type: Boolean, default: false },
    isBalanceSheet:    { type: Boolean, default: false },

    isSystem:  { type: Boolean, default: false },
    isActive:  { type: Boolean, default: true },
    description: { type: String, default: '' },

    // null for seeded accounts (no "user" created them)
    createdBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },
  },
  {
    timestamps: true,
    collection: 'accounts',
  }
)

AccountSchema.index({ code: 1 },          { unique: true })
AccountSchema.index({ type: 1, isActive: 1 })
AccountSchema.index({ subtype: 1 })        // fast lookup by subtype for auto-posting

export const Account: Model<IAccount> =
  mongoose.models.Account ||
  mongoose.model<IAccount>('Account', AccountSchema)